---

- name: "add nginx repository"
  tags: nginx
  apt_repository: repo='ppa:nginx/stable'
  sudo: yes

- name: "install nginx"
  tags: nginx
  apt: pkg=nginx state=latest
  sudo: yes
  notify:
    - start nginx

- name: "disable default site"
  tags: nginx
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes
