---

- name: "install mysql-server and related packages"
  tags: mysql
  apt: pkg={{item}} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-mysqldb
  sudo: yes
  notify:
    - start mysql

- name: "set mysql root pasword to {{mysql.root_password}}"
  tags: mysql
  mysql_user: name=root host={{item}} password={{mysql.root_password}} priv=*.*:ALL,GRANT
  sudo: yes
  with_items:
    - "{{ansible_hostname}}"
    - 127.0.0.1
    - ::1
    - localhost

- name: "create .my.cnf configuration file"
  tags: mysql
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  sudo: yes
